Update to v0.14.0-rc3
purescript-web/purescript-web-file pull request #13
Opened 2020-12-08 14:31 UTC by JordanMartinez

Backlinking to purescript-contrib/governance#35

2020-12-08 14:48 UTC, JordanMartinez commented
CI fails with this error:
```
> eslint src && spago build '--censor-lib --strict'


/home/runner/work/purescript-web-file/purescript-web-file/src/Web/File/FileReader.js
Error:   1:11  error  'FileReader' is already defined as a built-in global variable  no-redeclare

✖ 1 problem (1 error, 0 warnings)
```

2020-12-08 22:26 UTC, kl0tl submitted a review, later dismissed
This happens because of the `/* global FileReader */` comment in src/Web/File/FileReader.js, we can remove it.

2020-12-08 22:35 UTC, kl0tl commented on spago.dhall
> +-}
Shall we remove this comment?

2020-12-09 01:00 UTC, thomashoneyman requested changes

2020-12-09 01:00 UTC, thomashoneyman commented on .github/workflows/ci.yml
> +on: [push, pull_request]
```suggestion
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
```

2020-12-09 01:01 UTC, thomashoneyman commented
We also need to update the Bower file to point to master.

2020-12-10 02:33 UTC, closed without merging